# Generated by Django 5.1.4 on 2025-02-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='dept_role',
            new_name='role_name',
        ),
    ]
